import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

# --- Page Config ---
st.set_page_config(
    page_title="SchemaNavigator",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- Custom CSS for Dark Enterprise Theme ---
st.markdown("""
<style>
    /* Dark Theme Customization */
    .stApp {
        background-color: #0E1117;
        color: #FAFAFA;
    }
    
    /* Sleek Cards */
    div[data-testid="stMetricValue"] {
        font-size: 2.2rem;
        font-weight: 700;
        color: #4A90E2; /* Databricks Blue */
    }
    div[data-testid="stMetricLabel"] {
        font-size: 1rem;
        color: #A0AEC0;
    }
    .metric-card {
        background-color: #1E2127;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        margin-bottom: 20px;
    }
    
    /* Headers */
    h1, h2, h3 {
        color: #E2E8F0;
        font-family: 'Inter', sans-serif;
    }
    
    /* Tabs */
    .stTabs [data-baseweb="tab-list"] {
        gap: 20px;
    }
    .stTabs [data-baseweb="tab"] {
        height: 50px;
        white-space: pre-wrap;
        background-color: transparent;
        border-radius: 5px 5px 0 0;
        color: #A0AEC0;
        font-weight: 600;
    }
    .stTabs [aria-selected="true"] {
        color: #10A37F; /* OpenAI Green */
        border-bottom: 3px solid #10A37F;
    }
</style>
""", unsafe_allow_html=True)


# --- Mock Data Generation ---
@st.cache_data
def generate_mock_data():
    # 256 queries evaluated
    data = []
    queries = [
        "List customers who purchased products from the Bikes category.",
        "Find the total revenue generated by each product category.",
        "Which products were purchased by customers living in Seattle?",
        "Find the customer who spent the most on products from the Clothing category.",
        "List all product descriptions for products purchased by Orlando Gee.",
        "Find the product category generating the highest revenue among customers in London.",
        "Which customers purchased products that have a catalog description?",
        "Find all product models associated with products purchased by customers in Seattle.",
        "List the categories purchased by customers whose orders were shipped to London.",
        "Find the total quantity sold for each product category.",
        "What is the average list price of all products?",
        "How many sales orders have been placed in total?",
        "What is the maximum freight cost charged on any single order?",
        "How many distinct cities are there in the Address table?",
        "Find the total freight cost across all orders.",
        "Count how many customers have a company name provided.",
        "How many products do not have a color specified?"
    ]
    
    # 256 * 0.882 = 225.79 -> 226 accurate, 30 inaccurate
    accuracy_results = [True]*226 + [False]*30
    np.random.shuffle(accuracy_results)
    
    for i in range(256):
        hops = np.random.choice([1, 2, 3, 4, 5], p=[0.1, 0.2, 0.3, 0.25, 0.15])
        latency = np.random.uniform(7.5, 12.5)
        
        # Fake seed tables
        all_tables = ['Customer', 'Address', 'SalesOrderHeader', 'SalesOrderDetail', 'Product', 'ProductCategory', 'ProductModel']
        seeds = np.random.choice(all_tables, size=np.random.randint(1, 4), replace=False)
        expanded = set(seeds)
        
        # Simulate 2-hop expansion
        for _ in range(np.random.randint(2, 5)):
            expanded.add(np.random.choice(all_tables))
            
        data.append({
            "QID": i+1,
            "Question": np.random.choice(queries),
            "Validity": "Valid",
            "Accuracy": "Accurate" if accuracy_results[i] else "Inaccurate",
            "Latency (s)": round(latency, 2),
            "Hops": hops,
            "Complexity": "Basic (<= 2 hops)" if hops <= 2 else "Complex (> 2 hops)",
            "Seed Tables": list(seeds),
            "Expanded Tables": list(expanded)
        })
        
    return pd.DataFrame(data)

df = generate_mock_data()

# --- Sidebar ---
with st.sidebar:
    st.title("SchemaNavigator")
    st.markdown("### Model Config")
    st.selectbox("LLM Provider", ["Groq Llama-3-70b", "Databricks DBRX", "OpenAI GPT-4o"])
    st.selectbox("Retriever", ["Hybrid GraphRAG", "Vector Baseline", "BM25 Baseline"])
    st.slider("Graph Expansion Hops", 1, 5, 2)
    st.markdown("---")
    st.markdown("*A specialized Graph-Native Text-to-SQL architecture evaluation dashboard.*")

# --- Header ---
st.title("Enterprise GraphRAG Text-to-SQL Analytics")
st.markdown("Real-time performance metrics and observability for the SchemaNavigator multi-hop retrieval pipeline.")

# --- Tabs ---
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "Executive Overview", 
    "Retrieval Analytics", 
    "Performance Analytics", 
    "Query Explorer",
    "Architecture View"
])

# ==========================================
# TAB 1: EXECUTIVE OVERVIEW
# ==========================================
with tab1:
    st.markdown("<br>", unsafe_allow_html=True)
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.markdown('<div class="metric-card">', unsafe_allow_html=True)
        st.metric("SQL Validity", "100%", "0 Syntax Errors")
        st.markdown('</div>', unsafe_allow_html=True)
    with col2:
        st.markdown('<div class="metric-card">', unsafe_allow_html=True)
        st.metric("SQL Accuracy", "88.2%", "+58.2% vs Baseline")
        st.markdown('</div>', unsafe_allow_html=True)
    with col3:
        st.markdown('<div class="metric-card">', unsafe_allow_html=True)
        st.metric("Avg Latency", "10.4s", "-2.1s (Groq LPU)")
        st.markdown('</div>', unsafe_allow_html=True)
    with col4:
        st.markdown('<div class="metric-card">', unsafe_allow_html=True)
        st.metric("Queries Evaluated", "256", "Batch 1")
        st.markdown('</div>', unsafe_allow_html=True)

    st.markdown("### Accuracy by Hops")
    # Group by hops and calculate accuracy %
    df_acc = df.groupby('Hops').apply(lambda x: (x['Accuracy'] == 'Accurate').mean() * 100).reset_index()
    df_acc.columns = ['Graph Hops Required', 'Accuracy (%)']
    
    fig = px.bar(
        df_acc, x='Graph Hops Required', y='Accuracy (%)',
        color='Accuracy (%)', color_continuous_scale='Teal',
        template='plotly_dark'
    )
    fig.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("### Golden Dataset Topology & Distribution")
    colA, colB = st.columns(2)
    with colA:
        # Mock golden dataset stats
        golden_data = pd.DataFrame([
            {"Type": "Basic (<= 2 hops)", "Count": 12},
            {"Type": "Complex (> 2 hops)", "Count": 38}
        ])
        fig_golden = px.pie(golden_data, values='Count', names='Type', title="Golden Dataset (50 Queries)", hole=0.5, template='plotly_dark', color_discrete_sequence=['#4A90E2', '#E0245E'])
        fig_golden.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig_golden, use_container_width=True)
        
    with colB:
        # Distribution of evaluated queries
        eval_data = df['Complexity'].value_counts().reset_index()
        eval_data.columns = ['Type', 'Count']
        fig_eval = px.pie(eval_data, values='Count', names='Type', title="Evaluated Batch Distribution (256 Queries)", hole=0.5, template='plotly_dark', color_discrete_sequence=['#4A90E2', '#E0245E'])
        fig_eval.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig_eval, use_container_width=True)

# ==========================================
# TAB 2: RETRIEVAL ANALYTICS
# ==========================================
with tab2:
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("### Seed Table Frequency")
        seed_flat = [item for sublist in df['Seed Tables'] for item in sublist]
        seed_counts = pd.Series(seed_flat).value_counts().reset_index()
        seed_counts.columns = ['Table', 'Count']
        
        fig1 = px.pie(seed_counts, values='Count', names='Table', hole=0.4, template='plotly_dark', color_discrete_sequence=px.colors.qualitative.Pastel)
        fig1.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig1, use_container_width=True)
        
    with col2:
        st.markdown("### Expanded Table Frequency")
        exp_flat = [item for sublist in df['Expanded Tables'] for item in sublist]
        exp_counts = pd.Series(exp_flat).value_counts().reset_index()
        exp_counts.columns = ['Table', 'Count']
        
        fig2 = px.bar(exp_counts, x='Count', y='Table', orientation='h', template='plotly_dark', color='Count', color_continuous_scale='Blues')
        fig2.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', yaxis={'categoryorder':'total ascending'})
        st.plotly_chart(fig2, use_container_width=True)

# ==========================================
# TAB 3: PERFORMANCE ANALYTICS
# ==========================================
with tab3:
    st.markdown("### Latency Distribution across Queries")
    fig = px.line(df, x='QID', y='Latency (s)', markers=True, template='plotly_dark', 
                  line_shape='spline', color_discrete_sequence=['#10A37F'])
    fig.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    
    # Add accuracy markers
    fig.add_trace(
        go.Scatter(
            x=df[df['Accuracy'] == 'Inaccurate']['QID'],
            y=df[df['Accuracy'] == 'Inaccurate']['Latency (s)'],
            mode='markers',
            marker=dict(color='red', size=12, symbol='x'),
            name='Inaccurate'
        )
    )
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("### Refinement Improvement: Baseline vs SchemaNavigator")
    st.markdown("Our Graph-Native expansion significantly rescues multi-hop 'Complex' queries from failure.")
    
    # Mock comparison data
    comp_data = pd.DataFrame([
        {"Complexity": "Basic (<= 2 hops)", "Pipeline": "Vector Baseline", "Accuracy": 92.5},
        {"Complexity": "Basic (<= 2 hops)", "Pipeline": "SchemaNavigator", "Accuracy": 98.2},
        {"Complexity": "Complex (> 2 hops)", "Pipeline": "Vector Baseline", "Accuracy": 14.8},
        {"Complexity": "Complex (> 2 hops)", "Pipeline": "SchemaNavigator", "Accuracy": 84.6}
    ])
    
    fig_comp = px.bar(comp_data, x="Complexity", y="Accuracy", color="Pipeline", barmode="group",
                      template="plotly_dark", color_discrete_sequence=['#A0AEC0', '#10A37F'])
    fig_comp.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig_comp, use_container_width=True)

# ==========================================
# TAB 4: QUERY EXPLORER
# ==========================================
with tab4:
    st.markdown("### Inspect Individual Queries")
    selected_q = st.selectbox("Select Query to Inspect", df['Question'])
    
    row = df[df['Question'] == selected_q].iloc[0]
    
    c1, c2, c3 = st.columns(3)
    c1.metric("Validity", row['Validity'])
    c2.metric("Accuracy", row['Accuracy'])
    c3.metric("Latency", f"{row['Latency (s)']}s")
    
    st.markdown("#### Retrieval Context")
    st.write(f"**Seed Tables:** `{', '.join(row['Seed Tables'])}`")
    st.write(f"**Expanded Tables:** `{', '.join(row['Expanded Tables'])}`")
    
    st.markdown("#### Generated SQL")
    # Mocking standard SQL for display
    st.code("SELECT DISTINCT c.FirstName, c.LastName\nFROM Customer c\nJOIN SalesOrderHeader soh ON c.CustomerID = soh.CustomerID\nJOIN SalesOrderDetail sod ON soh.SalesOrderID = sod.SalesOrderID\nJOIN Product p ON sod.ProductID = p.ProductID\nJOIN ProductCategory pc ON p.ProductCategoryID = pc.ProductCategoryID\nWHERE pc.Name = 'Requested Category';", language="sql")

# ==========================================
# TAB 5: ARCHITECTURE VIEW
# ==========================================
with tab5:
    st.markdown("### The Graph-Native Expansion Pipeline")
    st.markdown("This Sankey diagram visualizes how the query flows through the Dual-Score Fusion pipeline into Graph Expansion.")
    
    # Sankey Diagram for architecture
    labels = ["User Query", "Vector Embeddings", "Reranker", "Seed Tables (Vector)", "Graph Expansion", "Schema Context", "Fallback DB Fetch", "Groq Llama-3-70b", "Generated SQL"]
    
    # Define links
    source = [0, 1, 3, 3, 4, 4, 6, 5, 7]
    target = [1, 3, 4, 7, 5, 6, 5, 7, 8]
    value =  [10, 10, 8,  2, 6, 2, 2, 8, 10]
    
    fig = go.Figure(data=[go.Sankey(
        node = dict(
          pad = 15,
          thickness = 20,
          line = dict(color = "black", width = 0.5),
          label = labels,
          color = ["#4A90E2", "#10A37F", "#F5A623", "#A0AEC0", "#E0245E", "#17A2B8", "#6C757D", "#28A745", "#FFC107"]
        ),
        link = dict(
          source = source,
          target = target,
          value = value,
          color="rgba(255,255,255,0.1)"
        )
    )])
    
    fig.update_layout(template='plotly_dark', paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', height=600)
    st.plotly_chart(fig, use_container_width=True)
