[project]
name = "ragas-mlflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "en-core-web-sm",
    "fastapi>=0.136.3",
    "groq>=1.4.0",
    "mlflow>=3.13.0",
    "networkx>=3.6.1",
    "ollama>=0.6.2",
    "pandas>=2.3.3",
    "ragas>=0.4.3",
    "sentence-transformers>=5.5.1",
    "spacy>=3.8.14",
    "sqlalchemy>=2.0.50",
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
